[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
solc = "0.8.19"

[rpc_endpoints]
base = "${RPC_URL}"
base_sepolia = "https://sepolia.base.org"

# Optimizer settings
optimizer = true
optimizer_runs = 200

# Testing
fuzz = { runs = 256 }

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = true